apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streamlit-cert
  namespace: streamlit
spec:
  secretName: streamlit-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - tcg-toolkit.com