services:
  streamlit-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit-dev
    container_name: streamlit-dev
    volumes:
      - ../TCGScraper:/TCGScraper
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PYTHONUNBUFFERED=1
