apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tcg-toolkit-test
spec:
  project: default
  source:
    repoURL: git@github.com:ronaldmanganaro/TCGScraper.git
    path: k8s/deploy/overlays/test
    targetRevision: develop
  destination:
    name: k3s
    namespace: streamlit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true