apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit-app
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001
