apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - frontend-ingress.yaml
  - frontend-service.yaml
  - certificate.yaml

patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-env.yaml
